package to.etc.prjbuilder.maker;

import to.etc.prjbuilder.builder.*;
import to.etc.prjbuilder.util.*;

/**
 * Products that are generated by a build need to implement this
 * interface.
 *
 * @author <a href="mailto:jal@etc.to">Frits Jalvingh</a>
 * Created on Mar 18, 2008
 */

public interface GeneratedProduct extends Product {
	public void generate(ModuleBuildInfo root, Reporter r) throws Exception;
}
